# Generated by Django 5.1.1 on 2024-09-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('sargenteante', 'Sargenteante'), ('comum', 'Comum'), ('rancheiro', 'Rancheiro')], default='comum', max_length=50),
        ),
    ]
