# Generated by Django 5.1.1 on 2024-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arranchamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_arranchamento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_refeicao', models.CharField(choices=[('CAFE', 'Café da Manhã'), ('ALMO', 'Almoço'), ('JANT', 'Jantar'), ('CEIA', 'Ceia')], max_length=4)),
                ('data_refeicao', models.DateField()),
            ],
        ),
    ]
