# Generated by Django 5.1.1 on 2024-09-18 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arranchamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arranchamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='refeicao',
            unique_together={('tipo_refeicao', 'data_refeicao')},
        ),
        migrations.AddField(
            model_name='arranchamento',
            name='refeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arranchamento.refeicao'),
        ),
        migrations.AlterUniqueTogether(
            name='arranchamento',
            unique_together={('usuario', 'refeicao')},
        ),
    ]
