# Generated by Django 5.1.1 on 2024-09-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arranchamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subunidade',
            field=models.CharField(choices=[('1ª Cia Fuz Mec', '1ª Companhia de Fuzileiros Mecanizada'), ('2ª Cia Fuz Mec', '2ª Companhia de Fuzileiros Mecanizada'), ('Cia C Ap', 'Companhia de Comando e Apoio'), ('SIBld', 'Seção de Instrução de Blindados'), ('NPOR', 'Núcleo de Preparação de Oficiais da Reserva'), ('CIOU', 'Centro de Instrução de Operações Urbanas'), ('EM', 'Estado Maior')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Subunidade',
        ),
    ]
