# Generated by Django 5.1.1 on 2024-09-06 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arranchamento', '0002_alter_customuser_subunidade_delete_subunidade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refeicao',
            unique_together={('tipo', 'data')},
        ),
        migrations.RemoveField(
            model_name='refeicao',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Arranchamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_arranchamento', models.DateTimeField(auto_now_add=True)),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arranchamento.refeicao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arranchamento.customuser')),
            ],
            options={
                'unique_together': {('usuario', 'refeicao')},
            },
        ),
    ]
