# Generated by Django 5.1.1 on 2024-09-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arranchamento', '0003_alter_refeicao_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refeicao',
            old_name='data',
            new_name='data_refeicao',
        ),
        migrations.RenameField(
            model_name='refeicao',
            old_name='tipo',
            new_name='tipo_refeicao',
        ),
        migrations.AlterUniqueTogether(
            name='refeicao',
            unique_together={('tipo_refeicao', 'data_refeicao')},
        ),
    ]
